include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 10.20.0.5     # Фиксированный IP в новой подсети
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DB}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 10.20.0.10    # Фиксированный IP в новой подсети
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24      # Новая бесконфликтная подсеть

volumes:
  db_data:

