# --- Этап 1: Сборка зависимостей (Builder) ---
FROM python:3.12-slim AS builder

WORKDIR /app

COPY requirements.txt .

# Устанавливаем зависимости локально для пользователя, чтобы легко скопировать их
RUN pip install --no-cache-dir --user -r requirements.txt

# --- Этап 2: Финальный легковесный образ (Runner) ---
FROM python:3.12-slim AS runner

WORKDIR /app

# Копируем только установленные библиотеки из этапа сборки
COPY --from=builder /root/.local /root/.local
# Копируем исходный код приложения
COPY . .

# Добавляем путь к установленным пакетам в PATH приложения
ENV PATH=/root/.local/bin:$PATH

# Команда запуска строго по условию задачи 1
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]

